Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import openpnm as op
pn = op.network.Cubic([4, 4,])
geo = op.geometry.SpheresAndCylinders(network=pn, pores=pn.Ps, throats=pn.Ts)
air = op.phases.Air(network=pn)
phys = op.physics.Basic(network=pn, phase=air, geometry=geo)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mopenpnm[39;00m [38;5;28;01mas[39;00m [38;5;21;01mop[39;00m
[1;32m      2[0m pn [38;5;241m=[39m op[38;5;241m.[39mnetwork[38;5;241m.[39mCubic([[38;5;241m4[39m, [38;5;241m4[39m,])
[0;32m----> 3[0m geo [38;5;241m=[39m [43mop[49m[38;5;241;43m.[39;49m[43mgeometry[49m[38;5;241m.[39mSpheresAndCylinders(network[38;5;241m=[39mpn, pores[38;5;241m=[39mpn[38;5;241m.[39mPs, throats[38;5;241m=[39mpn[38;5;241m.[39mTs)
[1;32m      4[0m air [38;5;241m=[39m op[38;5;241m.[39mphases[38;5;241m.[39mAir(network[38;5;241m=[39mpn)
[1;32m      5[0m phys [38;5;241m=[39m op[38;5;241m.[39mphysics[38;5;241m.[39mBasic(network[38;5;241m=[39mpn, phase[38;5;241m=[39mair, geometry[38;5;241m=[39mgeo)

[0;31mAttributeError[0m: module 'openpnm' has no attribute 'geometry'
AttributeError: module 'openpnm' has no attribute 'geometry'

